site_name: callingcards
site_description: A database of Scerevisiae calling cards data
repo_url: https://github.com/cmatkhan/yeast_cc_db
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/cmatkhan">cmatkhan</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
