"""
.. module:: ChipExo
   :synopsis: Module for the `ChipExo` model that stores ChIP-seq
              experiments for the Harbison lab. Currently, this stores the 
              data generated by yiming for the DTO paper.

.. moduleauthor:: Chase Mateusiak
.. date:: 2023-06-12
"""
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator  # pylint: disable=import-error # noqa # type: ignore
from .BaseModel import BaseModel
from .constants import P_VAL_DECIMAL_PLACES, P_VAL_MAX_DIGITS


class ChipExoQuerySet(models.QuerySet):
    def with_annotations(self):
        return self\
            .select_related(
                'tf',
                'gene',
                'gene__genepromoter'
            )\
            .annotate(
                tf_locus_tag=models.F('tf__locus_tag'),
                tf_gene=models.F('tf__gene'),
                target_locus_tag=models.F('gene__locus_tag'),
                target_gene=models.F('gene__gene'),
                target_gene_id=models.F('gene_id'),
                binding_signal=models.F('pval'),
                promoter_id=models.F('gene__genepromoter__id'),
                experiment=models.Value('chipexo_yiming'))\
            .values('tf_id', 'tf_locus_tag', 'tf_gene',
                    'target_gene_id', 'target_locus_tag', 'target_gene',
                    'binding_signal', 'experiment', 'promoter_id')


class ChipExo(BaseModel):
    """
    A model for storing Chip Exo experiments.

    Fields:
        - `gene`: ForeignKey to the `Gene` model, representing the gene that 
          was targeted in the ChIP-seq experiment.
        - `tf`: ForeignKey to the `Gene` model, representing the transcription
          factor that was used in the ChIP-seq experiment.
        - `pval`: DecimalField with a max digits of 6 and decimal places of 4,
          representing the p-value of the ChIP-seq experiment.

    Example usage:

    .. code-block:: python

        from callingcards.models import HarbisonChIP

        # get all HarbisonChIP records
        all_chipexo = chipexo.objects.all()

    """
    objects = ChipExoQuerySet.as_manager()

    # note that foreignkey fields automatically
    # create an index on the field
    gene = models.ForeignKey(
        'Gene',
        models.PROTECT,
        related_name='chipexo_target',
        db_index=True)
    tf = models.ForeignKey(
        'Gene',
        models.PROTECT,
        related_name='chipexo_tf',
        db_index=True)
    pval = models.DecimalField(
        validators=[MinValueValidator(0), MaxValueValidator(1)],
        max_digits=P_VAL_MAX_DIGITS,
        decimal_places=P_VAL_DECIMAL_PLACES
    )

    class Meta:
        managed = True
        db_table = 'chipexo'
