#Generated by Django 4.2 on 2023-04-28 11:59

import callingcards.callingcards.models.filepaths.cc_replicate_sig_filepath
import callingcards.callingcards.models.filepaths.qbed_filepath
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CCExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callingcards.cctf')),
                ('batch', models.CharField(max_length=15)),
                ('batch_replicate', models.PositiveSmallIntegerField(default=1)),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cc_experiment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChrMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('refseq', models.CharField(max_length=12)),
                ('igenomes', models.CharField(max_length=12)),
                ('ensembl', models.CharField(max_length=12)),
                ('ucsc', models.CharField(max_length=12)),
                ('mitra', models.CharField(max_length=15)),
                ('seqlength', models.PositiveIntegerField()),
                ('numbered', models.CharField(max_length=12)),
                ('chr', models.CharField(max_length=12)),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chr_map',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start', models.PositiveIntegerField(db_index=True)),
                ('end', models.PositiveIntegerField(db_index=True)),
                ('strand', models.CharField(choices=[('+', '+'), ('-', '-'), ('*', '*')], db_index=True, default='*', max_length=1)),
                ('type', models.CharField(default='unknown', max_length=30)),
                ('gene_biotype', models.CharField(default='unknown', max_length=20)),
                ('locus_tag', models.CharField(default='unknown', max_length=20, unique=True)),
                ('gene', models.CharField(default='unknown', max_length=20)),
                ('source', models.CharField(max_length=50)),
                ('alias', models.CharField(default='unknown', max_length=150)),
                ('note', models.CharField(default='none', max_length=1000)),
                ('chr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='callingcards.chrmap')),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gene',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QcTfToTransposon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('edit_dist', models.IntegerField()),
                ('tally', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)])),
                ('note', models.CharField(default='none', max_length=100)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callingcards.ccexperiment')),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qc_tf_to_transposon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QcR2ToR1Tf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('edit_dist', models.IntegerField()),
                ('tally', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)])),
                ('note', models.CharField(default='none', max_length=100)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callingcards.ccexperiment')),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qc_r2_to_r1_tf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QcR1ToR2Tf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('edit_dist', models.PositiveSmallIntegerField()),
                ('tally', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)])),
                ('note', models.CharField(default='none', max_length=100)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callingcards.ccexperiment')),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qc_r1_to_r2_tf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QcMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('total_reads', models.PositiveIntegerField()),
                ('unmapped', models.PositiveIntegerField()),
                ('multimapped', models.PositiveIntegerField()),
                ('genome_mapped', models.PositiveIntegerField()),
                ('plasmid_mapped', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)])),
                ('hpaii', models.PositiveIntegerField()),
                ('hinp1i', models.PositiveIntegerField()),
                ('taqai', models.PositiveIntegerField()),
                ('undet', models.PositiveIntegerField()),
                ('note', models.CharField(default='none', max_length=50)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callingcards.ccexperiment')),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qc_alignment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QcManualReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('rank_recall', models.CharField(choices=[('pass', 'pass'), ('fail', 'fail'), ('unreviewed', 'unreviewed'), ('note', 'note')], default='unreviewed', max_length=10)),
                ('chip_better', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('unreviewed', 'unreviewed'), ('note', 'note')], default='unreviewed', max_length=10)),
                ('data_usable', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('unreviewed', 'unreviewed'), ('note', 'note')], default='unreviewed', max_length=10)),
                ('passing_replicate', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('unreviewed', 'unreviewed'), ('note', 'note')], default='unreviewed', max_length=10)),
                ('note', models.CharField(default='none', max_length=100)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callingcards.ccexperiment')),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qc_manual_review',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PromoterRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start', models.PositiveIntegerField(db_index=True)),
                ('end', models.PositiveIntegerField(db_index=True)),
                ('strand', models.CharField(choices=[('+', '+'), ('-', '-'), ('*', '*')], db_index=True, default='*', max_length=1)),
                ('score', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)])),
                ('source', models.CharField(choices=[('not_orf', 'not_orf'), ('yiming', 'yiming')], db_index=True, max_length=10)),
                ('associated_feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genepromoter', to='callingcards.gene')),
                ('chr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='callingcards.chrmap')),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promoter_regions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='McIsaacZEV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('effect', models.DecimalField(decimal_places=28, max_digits=33)),
                ('pval', models.DecimalField(decimal_places=28, default=0.0, max_digits=29, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mcisaaczev_target', to='callingcards.gene')),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('tf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mcisaaczev_tf', to='callingcards.gene')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mcisaac_zev',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KemmerenTFKO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('effect', models.DecimalField(decimal_places=28, max_digits=33)),
                ('padj', models.DecimalField(decimal_places=28, max_digits=29, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kemmerentfko_target', to='callingcards.gene')),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('tf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kemmerentfko_tf', to='callingcards.gene')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kemmeren_tfko',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start', models.PositiveIntegerField(db_index=True)),
                ('end', models.PositiveIntegerField(db_index=True)),
                ('strand', models.CharField(choices=[('+', '+'), ('-', '-'), ('*', '*')], db_index=True, default='*', max_length=1)),
                ('depth', models.PositiveIntegerField()),
                ('chr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='callingcards.chrmap')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callingcards.ccexperiment')),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hops',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HarbisonChIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pval', models.DecimalField(decimal_places=28, max_digits=29, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harbisonchip_target', to='callingcards.gene')),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('tf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harbisonchip_tf', to='callingcards.gene')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'harbison_chip',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CCTF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('strain', models.CharField(default='unknown', max_length=20)),
                ('under_development', models.BooleanField(default=False)),
                ('notes', models.CharField(default='none', max_length=50)),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('tf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='callingcards.gene')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cc_tf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start', models.PositiveIntegerField(db_index=True)),
                ('end', models.PositiveIntegerField(db_index=True)),
                ('strand', models.CharField(choices=[('+', '+'), ('-', '-'), ('*', '*')], db_index=True, default='*', max_length=1)),
                ('depth', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('dsir4', 'dsir4'), ('adh1', 'adh1')], db_index=True, max_length=5)),
                ('chr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='callingcards.chrmap')),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'background',
                'managed': True,
            },
        ),
    ]
