# Generated by Django 4.1.7 on 2023-04-17 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callingcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcr1tor2tf',
            name='tally',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='qcr2tor1tf',
            name='tally',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='qctftotransposon',
            name='tally',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
