# Generated by Django 4.2 on 2023-04-28 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callingcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundSource',
            fields=[
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('providence', models.CharField(default='none', max_length=100)),
                ('notes', models.CharField(default='none', max_length=500)),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BackgroundSource',
                'db_table': 'backgroundsource',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PromoterRegionsSource',
            fields=[
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('providence', models.CharField(default='none', max_length=100)),
                ('notes', models.CharField(default='none', max_length=500)),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PromoterRegionsSource',
                'db_table': 'promoterregionssource',
                'managed': True,
            },
        ),
    ]
