# Generated by Django 4.2 on 2023-04-28 12:59

import callingcards.callingcards.models.filepaths.cc_replicate_sig_filepath
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callingcards', '0002_create_promoter_and_background_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callingcards.backgroundsource'),
        )
    ]
