# Generated by Django 4.2 on 2023-04-25 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callingcards', '0003_remove_promoterregions_associated_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='modifiedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ccexperiment',
            name='modifiedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cctf',
            name='modifiedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chrmap',
            name='modifiedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gene',
            name='modifiedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='harbisonchip',
            name='modifiedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hops',
            name='modifiedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kemmerentfko',
            name='modifiedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mcisaaczev',
            name='modifiedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='promoterregions',
            name='modifiedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qcmanualreview',
            name='modifiedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qcmetrics',
            name='modifiedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qcr1tor2tf',
            name='modifiedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qcr2tor1tf',
            name='modifiedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qctftotransposon',
            name='modifiedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HopsReplicateSig',
        ),
    ]
