# Generated by Django 4.2 on 2023-04-28 13:10

import callingcards.callingcards.models.filepaths.cc_replicate_sig_filepath
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callingcards', '0004_alter_promoterregions_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallingCardsSig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=callingcards.callingcards.models.filepaths.cc_replicate_sig_filepath.cc_replicate_sig_filepath)),
                ('notes', models.CharField(default='none', max_length=50)),
                ('background_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callingcards.backgroundsource')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callingcards.ccexperiment')),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('promoter_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callingcards.promoterregionssource')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CallingCardsSig',
                'db_table': 'callingcardssig',
                'ordering': ['experiment', 'promoter_source', 'background_source'],
                'managed': True,
                'unique_together': {('experiment', 'promoter_source', 'background_source')},
            },
        ),
    ]
