# Generated by Django 4.2 on 2023-05-09 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callingcards', '0007_hops_s3_chr_format_hopssource'),
    ]

    operations = [
        migrations.AddField(
            model_name='hops_s3',
            name='source',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='callingcards.hopssource'),
            preserve_default=False,
        ),
    ]
