# Generated by Django 4.2 on 2023-05-11 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callingcards', '0009_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccexperiment',
            name='lab',
            field=models.ForeignKey(default='brent', on_delete=django.db.models.deletion.CASCADE, to='callingcards.lab'),
            preserve_default=False,
        ),
    ]
