# Generated by Django 4.2 on 2023-06-12 19:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callingcards', '0010_ccexperiment_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChipExo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pval', models.DecimalField(decimal_places=28, max_digits=29, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chipexo_target', to='callingcards.gene')),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('tf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chipexo_tf', to='callingcards.gene')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chipexo',
                'managed': True,
            },
        ),
    ]
