# Generated by Django 4.2 on 2023-06-12 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callingcards', '0011_chipexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chipexo',
            name='pval',
        ),
        migrations.AddField(
            model_name='chipexo',
            name='strength',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000.0)]),
            preserve_default=False,
        ),
    ]
