# Generated by Django 4.2 on 2023-06-20 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callingcards', '0012_remove_chipexo_pval_chipexo_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='callingcardssig',
            name='hops_source',
            field=models.ForeignKey(default='mitra', on_delete=django.db.models.deletion.CASCADE, to='callingcards.hopssource'),
            preserve_default=False,
        ),
    ]
