# Generated by Django 4.2 on 2023-06-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callingcards', '0013_callingcardssig_hops_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callingcardssig',
            options={'managed': True, 'ordering': ['experiment', 'hops_source', 'promoter_source', 'background_source'], 'verbose_name': 'CallingCardsSig'},
        ),
        migrations.AlterUniqueTogether(
            name='callingcardssig',
            unique_together={('experiment', 'hops_source', 'promoter_source', 'background_source')},
        ),
    ]
