# Generated by Django 4.2 on 2023-06-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callingcards', '0014_alter_callingcardssig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chrmap',
            name='genomic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hops_s3',
            name='genomic_hops',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hops_s3',
            name='plasmid_hops',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
