# Generated by Django 4.2 on 2023-06-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callingcards', '0015_chrmap_genomic_hops_s3_genomic_hops_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chrmap',
            name='genomic',
        ),
        migrations.AddField(
            model_name='chrmap',
            name='type',
            field=models.CharField(choices=[('genomic', 'genomic'), ('mito', 'mito'), ('plasmid', 'plasmid')], default='genomic', max_length=8),
        ),
        migrations.AddField(
            model_name='hops_s3',
            name='mito_hops',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
